resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

jobs:
- job: Windows_MSVC
  variables:
    VULKAN_SDK: "$(Build.SourcesDirectory)\\kotek-engine-deps-win32\\VulkanSDK\\"
  pool:
    vmImage: windows-2019

  steps:
  - script: |
    git config --global --add filter.lfs.required true
    git config --global --add filter.lfs.smudge "git-lfs smudge -- %f"
    git config --global --add filter.lfs.process "git-lfs filter-process"
    git config --global --add filter.lfs.clean "git-lfs clean -- %f"
  - checkout: self
    lfs: true
    submodules: true
  - script: mkdir build
  - script: 'echo "$(Build.SourcesDirectory)"'
    displayName: Make build directory

  - task: CMake@1
    displayName: 'Generate Solution Files'
    inputs:
      cmakeArgs: '-DCMAKE_BUILD_TYPE=Debug ../'


  - task: VSBuild@1
    displayName: 'Build solution kotek.engine.sln'
    inputs:
      solution: 'build/kotek.engine.sln'
      platform: 'x64'
      configuration: 'Debug'