if (WIN32)
    find_program(NUGET_COMMAND nuget)
    if(NOT NUGET_COMMAND)
        message("NuGet not found in PATH!")
        message("Downloading NuGet...")
        if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/nuget")
            execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_SOURCE_DIR}/nuget")
            file(DOWNLOAD https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
                "${CMAKE_CURRENT_SOURCE_DIR}/nuget/nuget.exe")
        endif()
        set(NUGET_COMMAND "${CMAKE_BINARY_DIR}/nuget/nuget.exe")
        message("NuGet downloaded: ${NUGET_COMMAND}")
    else()
        message("NuGet found: ${NUGET_COMMAND}")
    endif()
endif()
