#pragma once

#ifdef KOTEK_OPENGL
	#define KOTEK_USE_OPENGL
	#define KOTEK_USE_OPENGL_MODERN_VERSION 3
	#define KOTEK_USE_OPENGL_LEGACY_VERSION 3

	#define KOTEK_DEF_RENDER_GL_ES_INDIRECT_DRAWING_TOTAL_COMMANDS 50
	#define KOTEK_DEF_RENDER_GL_ES_GEOMETRY_MANAGER_MAX_BUFFERS_COUNT 8
	#define KOTEK_DEF_RENDER_GL_ES_GEOMETRY_MANAGER_REALLOCATION_ENABLED 1

	#define KOTEK_DEF_RENDER_GL_INDIRECT_DRAWING_TOTAL_COMMANDS 50
	#define KOTEK_DEF_RENDER_GL_GEOMETRY_MANAGER_MAX_BUFFERS_COUNT 8
	#define KOTEK_DEF_RENDER_GL_GEOMETRY_MANAGER_REALLOCATION_ENABLED 1
	#define KOTEK_DEF_RENDER_GL_BINDLESS_TEXTURE_ENABLED 1

	// render graph simplified
	#define KOTEK_DEF_RENDER_GL_RENDER_GRAPH_SIMPLIFIED_MAX_PASS_COUNT 32
#endif
