#pragma once

#include "kotek_std_alias_char_model.h"

KOTEK_BEGIN_NAMESPACE_KOTEK
KOTEK_BEGIN_NAMESPACE_CORE

class ktkMainManager;

KOTEK_END_NAMESPACE_CORE
KOTEK_END_NAMESPACE_KOTEK

KOTEK_BEGIN_NAMESPACE_KOTEK
KOTEK_BEGIN_NAMESPACE_CORE

bool InitializeModule_Core_Types_Char(ktkMainManager* p_manager);
bool SerializeModule_Core_Types_Char(ktkMainManager* p_manager);
bool DeserializeModule_Core_Types_Char(ktkMainManager* p_manager);
bool ShutdownModule_Core_Types_Char(ktkMainManager* p_manager);

KOTEK_END_NAMESPACE_CORE
KOTEK_END_NAMESPACE_KOTEK
