#pragma once

#include "kotek_std_preprocessors.h"

KOTEK_BEGIN_NAMESPACE_KOTEK
KOTEK_BEGIN_NAMESPACE_CORE

class ktkMainManager;

KOTEK_END_NAMESPACE_CORE
KOTEK_END_NAMESPACE_KOTEK

KOTEK_BEGIN_NAMESPACE_KOTEK
KOTEK_BEGIN_NAMESPACE_CORE

bool InitializeModule_Core_Defines_Static_CPP(ktkMainManager*);
bool ShutdownModule_Core_Defines_Static_CPP(ktkMainManager*);
bool SerializeModule_Core_Defines_Static_CPP(ktkMainManager*);
bool DeserializeModule_Core_Defines_Static_CPP(ktkMainManager*);

KOTEK_END_NAMESPACE_CORE
KOTEK_END_NAMESPACE_KOTEK