#pragma once

#include <kotek.core.defines.static.cpp/include/kotek_core_defines_static_cpp.h>
#include "kotek_std_preprocessors.h"

KOTEK_BEGIN_NAMESPACE_KOTEK
KOTEK_BEGIN_NAMESPACE_CORE
class ktkMainManager;
KOTEK_END_NAMESPACE_CORE
KOTEK_END_NAMESPACE_KOTEK

KOTEK_BEGIN_NAMESPACE_KOTEK
KOTEK_BEGIN_NAMESPACE_CORE
bool InitializeModule_Core_Defines_Static_OS_Windows(ktkMainManager*);
bool ShutdownModule_Core_Defines_Static_OS_Windows(ktkMainManager*);
bool SerializeModule_Core_Defines_Static_OS_Windows(ktkMainManager*);
bool DeserializeModule_Core_Defines_Static_OS_Windows(ktkMainManager*);
KOTEK_END_NAMESPACE_CORE
KOTEK_END_NAMESPACE_KOTEK