#include "../include/kotek_plugin_override.h"

#include <kotek.core.main_manager/include/kotek_main_manager.h>
#include <kotek.core.main_manager/include/kotek_plugin_invoke.h>
#include <kotek.core.main_manager/include/kotek_plugin_state.h>
#include <kotek.core.api/include/kotek_api.h>
#include <kotek.core.defines_dependent.assert/include/kotek_std_dependent_preprocessors.h>

// generated by cmake/library.cmake kotek_generate_plugin_manifest() in EVERY
// linkage mode: the module-name <-> entry-symbol table of all modules that
// registered entry points through kotek_add_library
#include <kotek_plugin_registry.h>

#ifdef _WIN32
	#include <Windows.h>
#else
	#include <dlfcn.h>
	#include <sys/stat.h>
#endif

#if defined(KOTEK_DEBUG) && defined(_WIN32)
	#include <crtdbg.h>
#endif

#include <cstdio>
#include <cstdlib>
#include <cstring>

KOTEK_BEGIN_NAMESPACE_KOTEK
KOTEK_BEGIN_NAMESPACE_CORE

ktkPluginState::ktkPluginState(void) :
	m_override_slots{},
	m_plugins_dir{},
	m_override_initialized{false},
	m_invoke_handles{},
	m_invoke_handles_count{0}
{
	const char default_directory[] = "plugins";
	memcpy(this->m_plugins_dir, default_directory,
		sizeof(default_directory));
}

namespace
{
	/// @brief \~english plugins.json is a small flat map; 64 KiB is orders of
	/// magnitude more than ~150 modules need, anything bigger is rejected
	constexpr unsigned long k_max_json_size = 64 * 1024;

#ifdef _WIN32
	void* override_load(const char* p_dll_path)
	{
		return reinterpret_cast<void*>(LoadLibraryA(p_dll_path));
	}
	void* override_sym(void* handle, const char* p_symbol)
	{
		return reinterpret_cast<void*>(
			GetProcAddress(reinterpret_cast<HMODULE>(handle), p_symbol));
	}
	bool override_file_exists(const char* p_path)
	{
		return GetFileAttributesA(p_path) != INVALID_FILE_ATTRIBUTES;
	}
	void override_make_dir(const char* p_path)
	{
		// ERROR_ALREADY_EXISTS is the expected non-error case
		CreateDirectoryA(p_path, nullptr);
	}
#else
	void* override_load(const char* p_dll_path)
	{
		return dlopen(p_dll_path, RTLD_NOW | RTLD_LOCAL);
	}
	void* override_sym(void* handle, const char* p_symbol)
	{
		return dlsym(handle, p_symbol);
	}
	bool override_file_exists(const char* p_path)
	{
		FILE* p_file = fopen(p_path, "rb");
		if (p_file)
		{
			fclose(p_file);
			return true;
		}
		return false;
	}
	void override_make_dir(const char* p_path) { mkdir(p_path, 0755); }
#endif

	// joins "<dir>/<file>" with a bounds check; returns false on overflow
	bool override_join_path(char* p_out, unsigned long out_capacity,
		const char* p_dir, const char* p_file)
	{
		const unsigned long dir_length =
			static_cast<unsigned long>(strlen(p_dir));
		const unsigned long file_length =
			static_cast<unsigned long>(strlen(p_file));

		if (dir_length + 1 + file_length + 1 > out_capacity)
			return false;

		memcpy(p_out, p_dir, dir_length);
		p_out[dir_length] = '/';
		memcpy(p_out + dir_length + 1, p_file, file_length);
		p_out[dir_length + 1 + file_length] = '\0';
		return true;
	}

	// linear registry scan by module name; -1 when unknown
	long override_find_module(const char* p_module_name)
	{
		for (unsigned long i = 0; i < g_kotek_plugin_registry_count; ++i)
		{
			if (strcmp(g_kotek_plugin_registry[i].p_module_name,
					p_module_name) == 0)
				return static_cast<long>(i);
		}

		return -1;
	}

	void override_register(ktkPluginState* p_state,
		unsigned long module_index, const char* p_dll_file)
	{
		if (p_state->m_override_slots[module_index].m_state !=
			ePluginOverrideSlotState::kNone)
			return;

		if (override_join_path(
				p_state->m_override_slots[module_index].m_dll_path,
				KOTEK_DEF_PLUGIN_OVERRIDE_MAX_PATH,
				p_state->m_plugins_dir, p_dll_file) == false)
		{
			KOTEK_MESSAGE_WARNING(
				"[plugin override]: path too long, skipped: {}/{}",
				p_state->m_plugins_dir, p_dll_file);
			return;
		}

		p_state->m_override_slots[module_index].m_p_handle = nullptr;
		p_state->m_override_slots[module_index].m_state =
			ePluginOverrideSlotState::kRegistered;
	}

	/// @brief \~english minimal robust parser for the exact plugins.json
	/// schema {"modules": {"<module>": "<dll file>", ...}}; unknown
	/// top-level keys are skipped (values of any json shape), malformed
	/// input just stops registration — no exceptions, bounded buffers
	namespace json
	{
		struct cursor_t
		{
			const char* p_current;
			const char* p_end;
		};

		void skip_ws(cursor_t& cursor)
		{
			while (cursor.p_current < cursor.p_end)
			{
				const char c = *cursor.p_current;
				if (c != ' ' && c != '\t' && c != '\r' && c != '\n')
					break;
				++cursor.p_current;
			}
		}

		bool expect(cursor_t& cursor, char expected)
		{
			skip_ws(cursor);
			if (cursor.p_current < cursor.p_end &&
				*cursor.p_current == expected)
			{
				++cursor.p_current;
				return true;
			}
			return false;
		}

		// reads a "..." string into p_out (bounded); handles backslash
		// escapes by copying the escaped character literally
		bool read_string(cursor_t& cursor, char* p_out,
			unsigned long out_capacity)
		{
			skip_ws(cursor);

			if (cursor.p_current >= cursor.p_end ||
				*cursor.p_current != '"')
				return false;

			++cursor.p_current;

			unsigned long written = 0;
			while (cursor.p_current < cursor.p_end)
			{
				const char c = *cursor.p_current;

				if (c == '"')
				{
					++cursor.p_current;
					p_out[written] = '\0';
					return true;
				}

				if (c == '\\' && cursor.p_current + 1 < cursor.p_end)
					++cursor.p_current;

				if (written + 1 >= out_capacity)
					return false;

				p_out[written++] = *cursor.p_current;
				++cursor.p_current;
			}

			return false;
		}

		// skips a value of any json shape (string / object / array /
		// primitive) so unknown keys cannot desync the parser
		void skip_value(cursor_t& cursor)
		{
			skip_ws(cursor);

			if (cursor.p_current >= cursor.p_end)
				return;

			const char first = *cursor.p_current;

			if (first == '"')
			{
				++cursor.p_current;
				while (cursor.p_current < cursor.p_end)
				{
					const char c = *cursor.p_current;
					++cursor.p_current;
					if (c == '\\' && cursor.p_current < cursor.p_end)
						++cursor.p_current;
					else if (c == '"')
						return;
				}
				return;
			}

			if (first == '{' || first == '[')
			{
				unsigned long depth = 0;
				bool in_string = false;

				while (cursor.p_current < cursor.p_end)
				{
					const char c = *cursor.p_current;
					++cursor.p_current;

					if (in_string)
					{
						if (c == '\\' && cursor.p_current < cursor.p_end)
							++cursor.p_current;
						else if (c == '"')
							in_string = false;
						continue;
					}

					if (c == '"')
						in_string = true;
					else if (c == '{' || c == '[')
						++depth;
					else if (c == '}' || c == ']')
					{
						--depth;
						if (depth == 0)
							return;
					}
				}
				return;
			}

			// primitive (number / true / false / null)
			while (cursor.p_current < cursor.p_end)
			{
				const char c = *cursor.p_current;
				if (c == ',' || c == '}' || c == ']' || c == ' ' ||
					c == '\t' || c == '\r' || c == '\n')
					return;
				++cursor.p_current;
			}
		}

		void parse_modules_object(cursor_t& cursor, ktkPluginState* p_state)
		{
			if (expect(cursor, '{') == false)
				return;

			while (cursor.p_current < cursor.p_end)
			{
				if (expect(cursor, '}'))
					return;

				char module_name[256];
				char dll_file[256];

				if (read_string(cursor, module_name, sizeof(module_name)) ==
					false)
					return;
				if (expect(cursor, ':') == false)
					return;
				if (read_string(cursor, dll_file, sizeof(dll_file)) == false)
					return;

				const long module_index = override_find_module(module_name);
				if (module_index < 0)
				{
					KOTEK_MESSAGE_WARNING(
						"[plugin override]: plugins.json names unknown "
						"module '{}', ignored",
						module_name);
				}
				else
				{
					override_register(p_state,
						static_cast<unsigned long>(module_index), dll_file);
				}

				if (expect(cursor, ','))
					continue;
				if (expect(cursor, '}'))
					return;

				return;
			}
		}

		void parse_root(char* p_content, unsigned long content_size,
			ktkPluginState* p_state)
		{
			cursor_t cursor{p_content, p_content + content_size};

			if (expect(cursor, '{') == false)
				return;

			while (cursor.p_current < cursor.p_end)
			{
				if (expect(cursor, '}'))
					return;

				char key[64];

				if (read_string(cursor, key, sizeof(key)) == false)
					return;
				if (expect(cursor, ':') == false)
					return;

				if (strcmp(key, "modules") == 0)
					parse_modules_object(cursor, p_state);
				else
					skip_value(cursor);

				if (expect(cursor, ','))
					continue;
				if (expect(cursor, '}'))
					return;

				return;
			}
		}
	} // namespace json

	// variant B registration: plugins/plugins.json (wins over the name
	// convention because it runs first and marks the slots it fills)
	void override_scan_json(ktkPluginState* p_state)
	{
		char json_path[KOTEK_DEF_PLUGIN_OVERRIDE_MAX_PATH];
		if (override_join_path(json_path, sizeof(json_path),
				p_state->m_plugins_dir, "plugins.json") == false)
			return;

		FILE* p_file = fopen(json_path, "rb");
		if (p_file == nullptr)
			return;

		if (fseek(p_file, 0, SEEK_END) != 0)
		{
			fclose(p_file);
			return;
		}

		const long file_size = ftell(p_file);
		rewind(p_file);

		if (file_size <= 0)
		{
			fclose(p_file);
			return;
		}

		if (static_cast<unsigned long>(file_size) >= k_max_json_size)
		{
			KOTEK_MESSAGE_WARNING(
				"[plugin override]: plugins.json exceeds {} bytes, ignored",
				k_max_json_size);
			fclose(p_file);
			return;
		}

		char content[k_max_json_size];
		const size_t read_count =
			fread(content, 1, static_cast<size_t>(file_size), p_file);
		fclose(p_file);

		content[read_count] = '\0';
		json::parse_root(
			content, static_cast<unsigned long>(read_count), p_state);
	}

	// variant A registration: plugins/<module-folder-name>.dll present on
	// disk overrides that module's entries
	void override_scan_name_convention(ktkPluginState* p_state)
	{
		for (unsigned long i = 0; i < g_kotek_plugin_registry_count; ++i)
		{
			if (p_state->m_override_slots[i].m_state !=
				ePluginOverrideSlotState::kNone)
				continue;

			char file_name[KOTEK_DEF_PLUGIN_OVERRIDE_MAX_PATH];
			const char* p_module_name =
				g_kotek_plugin_registry[i].p_module_name;
			const unsigned long name_length =
				static_cast<unsigned long>(strlen(p_module_name));

			// "<module>.dll"
			if (name_length + 4 + 1 > sizeof(file_name))
				continue;

			memcpy(file_name, p_module_name, name_length);
			memcpy(file_name + name_length, ".dll", 4);
			file_name[name_length + 4] = '\0';

			char full_path[KOTEK_DEF_PLUGIN_OVERRIDE_MAX_PATH];
			if (override_join_path(full_path, sizeof(full_path),
					p_state->m_plugins_dir, file_name) == false)
				continue;

			if (override_file_exists(full_path))
				override_register(p_state, i, file_name);
		}
	}

	void override_ensure_initialized(ktkPluginState* p_state)
	{
		if (p_state->m_override_initialized)
			return;

		p_state->m_override_initialized = true;

		KOTEK_ASSERT(g_kotek_plugin_registry_count <=
				KOTEK_DEF_PLUGIN_OVERRIDE_MAX_MODULES,
			"[plugin override]: the generated module registry has {} modules "
			"but the override table is bounded at {} — raise "
			"KOTEK_DEF_PLUGIN_OVERRIDE_MAX_MODULES in kotek_plugin_state.h",
			g_kotek_plugin_registry_count,
			KOTEK_DEF_PLUGIN_OVERRIDE_MAX_MODULES);

		if (g_kotek_plugin_registry_count >
			KOTEK_DEF_PLUGIN_OVERRIDE_MAX_MODULES)
			return;

		override_scan_json(p_state);
		override_scan_name_convention(p_state);
	}
} // namespace

int ktkPluginTryOverride(ePluginOverrideVerb verb, const char* p_symbol_name,
	ktkMainManager* p_manager)
{
	if (p_symbol_name == nullptr || p_manager == nullptr)
		return -1;

	ktkPluginState* p_state = &p_manager->Get_PluginState();

	override_ensure_initialized(p_state);

	for (unsigned long i = 0; i < g_kotek_plugin_registry_count; ++i)
	{
		const char* p_entry_symbol = nullptr;

		switch (verb)
		{
		case ePluginOverrideVerb::kINIT:
			p_entry_symbol = g_kotek_plugin_registry[i].p_init_symbol;
			break;
		case ePluginOverrideVerb::kSHUTDOWN:
			p_entry_symbol = g_kotek_plugin_registry[i].p_shutdown_symbol;
			break;
		case ePluginOverrideVerb::kSERIALIZE:
			p_entry_symbol = g_kotek_plugin_registry[i].p_serialize_symbol;
			break;
		case ePluginOverrideVerb::kDESERIALIZE:
			p_entry_symbol = g_kotek_plugin_registry[i].p_deserialize_symbol;
			break;
		}

		if (p_entry_symbol == nullptr ||
			strcmp(p_entry_symbol, p_symbol_name) != 0)
			continue;

		ktkPluginOverrideSlot& slot = p_state->m_override_slots[i];

		if (slot.m_state == ePluginOverrideSlotState::kNone ||
			slot.m_state == ePluginOverrideSlotState::kFailed)
			return -1;

		if (slot.m_state == ePluginOverrideSlotState::kRegistered)
		{
			slot.m_p_handle = override_load(slot.m_dll_path);

			if (slot.m_p_handle == nullptr)
			{
				slot.m_state = ePluginOverrideSlotState::kFailed;
				KOTEK_MESSAGE_WARNING(
					"[plugin override]: failed to load override dll '{}' "
					"for module '{}', falling back to the built-in "
					"implementation",
					slot.m_dll_path, g_kotek_plugin_registry[i].p_module_name);
				return -1;
			}

			slot.m_state = ePluginOverrideSlotState::kLoaded;
		}

		void* p_function = override_sym(slot.m_p_handle, p_symbol_name);

		if (p_function == nullptr)
		{
			KOTEK_MESSAGE_WARNING(
				"[plugin override]: override dll '{}' does not export "
				"'{}', falling back to the built-in implementation",
				slot.m_dll_path, p_symbol_name);
			return -1;
		}

		const bool status =
			reinterpret_cast<ktkPluginModuleEntry_t>(p_function)(p_manager);
		return status ? 1 : 0;
	}

	return -1;
}

void ktkPluginOverrideStartup(ktkMainManager* p_manager)
{
	if (p_manager == nullptr)
		return;

	ktkPluginState* p_state = &p_manager->Get_PluginState();

	override_ensure_initialized(p_state);

	ktkIFrameworkConfig* p_config = p_manager->Get_EngineConfig();

	if (p_config == nullptr)
		return;

	const bool want_template = p_config->Is_PluginsTemplateRequested();
	const bool want_modules = p_config->Is_PluginsModulesRequested();

	if (want_template == false && want_modules == false)
		return;

	if (want_template)
	{
		const bool status =
			ktkPluginOverrideWriteTemplate(p_state->m_plugins_dir);
		printf("[plugin override]: %s %s/plugins.template.json\n",
			status ? "wrote" : "FAILED to write", p_state->m_plugins_dir);
		KOTEK_MESSAGE("[plugin override]: {} {}/plugins.template.json",
			status ? "wrote" : "FAILED to write", p_state->m_plugins_dir);
	}

	if (want_modules)
	{
		const bool status =
			ktkPluginOverrideWriteModulesList(p_state->m_plugins_dir);
		printf("[plugin override]: %s %s/plugins.modules.json\n",
			status ? "wrote" : "FAILED to write", p_state->m_plugins_dir);
		KOTEK_MESSAGE("[plugin override]: {} {}/plugins.modules.json",
			status ? "wrote" : "FAILED to write", p_state->m_plugins_dir);
	}

	// codegen flags are terminal: the file(s) are the whole job
#if defined(KOTEK_DEBUG) && defined(_WIN32)
	// kotek.core.memory.cpu force-enables the CRT exit leak dump
	// (_CRTDBG_LEAK_CHECK_DF); this path exits WITHOUT running the module
	// shutdowns where the dump is normally disabled again, and in a
	// multi-CRT process the dump walks cross-poisoned block lists into an
	// assert flood — disable it here, the same containment the kotek.exe
	// entry point applies (allocation tracking itself stays on)
	_CrtSetDbgFlag(_CrtSetDbgFlag(_CRTDBG_REPORT_FLAG) &
		~_CRTDBG_LEAK_CHECK_DF);
#endif
	exit(0);
}

bool ktkPluginOverrideWriteTemplate(const char* p_plugins_dir)
{
	if (p_plugins_dir == nullptr)
		return false;

	override_make_dir(p_plugins_dir);

	char path[KOTEK_DEF_PLUGIN_OVERRIDE_MAX_PATH];
	if (override_join_path(
			path, sizeof(path), p_plugins_dir, "plugins.template.json") ==
		false)
		return false;

	FILE* p_file = fopen(path, "wb");
	if (p_file == nullptr)
		return false;

	fputs("{\n\t\"modules\":\n\t{\n", p_file);

	for (unsigned long i = 0; i < g_kotek_plugin_registry_count; ++i)
	{
		fprintf(p_file, "\t\t\"%s\": \"\"%s\n",
			g_kotek_plugin_registry[i].p_module_name,
			(i + 1 < g_kotek_plugin_registry_count) ? "," : "");
	}

	fputs("\t}\n}\n", p_file);

	const bool status = ferror(p_file) == 0;
	fclose(p_file);
	return status;
}

bool ktkPluginOverrideWriteModulesList(const char* p_plugins_dir)
{
	if (p_plugins_dir == nullptr)
		return false;

	override_make_dir(p_plugins_dir);

	char path[KOTEK_DEF_PLUGIN_OVERRIDE_MAX_PATH];
	if (override_join_path(
			path, sizeof(path), p_plugins_dir, "plugins.modules.json") ==
		false)
		return false;

	FILE* p_file = fopen(path, "wb");
	if (p_file == nullptr)
		return false;

	fputs("[\n", p_file);

	for (unsigned long i = 0; i < g_kotek_plugin_registry_count; ++i)
	{
		fprintf(p_file, "\t\"%s\"%s\n",
			g_kotek_plugin_registry[i].p_module_name,
			(i + 1 < g_kotek_plugin_registry_count) ? "," : "");
	}

	fputs("]\n", p_file);

	const bool status = ferror(p_file) == 0;
	fclose(p_file);
	return status;
}

void ktkPluginOverrideSetDirectory(
	ktkMainManager* p_manager, const char* p_plugins_dir)
{
	if (p_manager == nullptr || p_plugins_dir == nullptr)
		return;

	const unsigned long length =
		static_cast<unsigned long>(strlen(p_plugins_dir));

	if (length + 1 > KOTEK_DEF_PLUGIN_OVERRIDE_MAX_PATH)
		return;

	char* p_directory = p_manager->Get_PluginState().m_plugins_dir;
	memcpy(p_directory, p_plugins_dir, length);
	p_directory[length] = '\0';
}

void ktkPluginOverrideResetForTests(ktkMainManager* p_manager)
{
	if (p_manager == nullptr)
		return;

	ktkPluginState* p_state = &p_manager->Get_PluginState();

	memset(p_state->m_override_slots, 0,
		sizeof(p_state->m_override_slots));
	p_state->m_override_initialized = false;
}

int ktkPluginOverrideFind(ktkMainManager* p_manager,
	const char* p_module_name, char* p_out_dll_path,
	unsigned long out_dll_path_capacity)
{
	if (p_manager == nullptr || p_module_name == nullptr)
		return 0;

	ktkPluginState* p_state = &p_manager->Get_PluginState();

	override_ensure_initialized(p_state);

	const long module_index = override_find_module(p_module_name);

	if (module_index < 0)
		return 0;

	const ktkPluginOverrideSlot& slot =
		p_state->m_override_slots[static_cast<unsigned long>(module_index)];

	if (slot.m_state == ePluginOverrideSlotState::kNone)
		return 0;

	if (p_out_dll_path && out_dll_path_capacity)
	{
		const unsigned long length =
			static_cast<unsigned long>(strlen(slot.m_dll_path));

		if (length + 1 <= out_dll_path_capacity)
		{
			memcpy(p_out_dll_path, slot.m_dll_path, length);
			p_out_dll_path[length] = '\0';
		}
		else
		{
			p_out_dll_path[0] = '\0';
		}
	}

	return 1;
}

KOTEK_END_NAMESPACE_CORE
KOTEK_END_NAMESPACE_KOTEK
